spring.application.name=api-gateway
spring.datasource.url=jdbc:postgresql://ep-bitter-credit-am578ocf-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Xn68PMAwbvdt
spring.datasource.driver-class-name=org.postgresql.Driver
# Cambia 'update' por 'create' por si les da error con la base de datos, pero tengan en cuenta que 
#create' eliminará y recreará las tablas cada vez que inicien la aplicación, pero es para que la imagen 
#de la base de datos sea la misma que la de las entidades, si no les da error con 'update' pueden dejarlo 
#así para que no se pierda la información cada vez que inicien la aplicación
# 2. ¿TE SALE ERROR? (Ej: "Duplicate entry", "Table not found", etc.)
#    Si el proyecto no arranca por culpa de la BD, cambia la línea de arriba
#    por 'create-drop' UNA SOLA VEZ y reinicia el backend.
#    
#spring.jpa.hibernate.ddl-auto=create-drop
#
#    (Esto borra todo y lo crea desde cero con los datos limpios. 
#     ¡Acuérdate de volver a ponerlo en 'update' después!)
# ==============================================================

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=EstaEsUnaClaveSuperSecretaYLoSuficientementeLargaParaQueFuncione2026
jwt.expiration=86400000
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# PUERTO PARA HUGGING FACE
server.port=7860